[package]
name = "rsmnl-derive"
version = "0.1.0"
authors = ["chamas <chamas@h4.dion.ne.jp>"]

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "*"
quote = "*"
syn = { version = "*", features = ["full", "extra-traits"] }
errno = "0.2.7"

